version: "3"
services:
  Hikka:
    container_name: "Hikka"
    build:
      context: .
    volumes:
      - Hikka:/data
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python -m hikka"
    ports:
      - "${EXTERNAL_PORT:-8080}:8080"

volumes:
  Hikka:
